# Main Docker Compose file
version: '3.8'

services:
  web-app:
    build:
      context: ./docker/web
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - lms-network
    volumes:
      - ./web-app:/app

  mobile-app:
    build:
      context: ./docker/mobile
    ports:
      - "19000:19000"   # Adjust for Expo or your mobile dev platform
    env_file:
      - .env
    networks:
      - lms-network
    volumes:
      - ./mobile-app:/app

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - lms-network
    volumes:
      - ./backend:/app

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - lms-network

volumes:
  postgres-data:

networks:
  lms-network:
    driver: bridge
